app_name: tradingview
app_shortcut_link: C:\Users\LENOVO\OneDrive\Desktop\TradingView.lnk
application:
  name: TradingView HotKeys Desktop App
  version: 1.0
auto_fit_hotkey: +
debug: true
hotkeys_mapping_method2:
  '*': Alt+f
  '-': Ctrl+Alt+h
  .: Alt+h
  '0': Alt+t
keys_for_quick_search:
- '1'
- +
- /
keys_for_time_interval:
- '2'
- '3'
- '4'
- '5'
- '6'
- '7'
- '8'
- '9'
keys_that_already_have_hotkeys:
  Fib: '*'
  Hide: '-'
  Horizontal Line: .
  Trend Line: '0'
log_level: info
numpad_keys_scancode:
- 28
- 53
- 55
- 74
- 71
- 72
- 73
- 78
- 75
- 76
- 77
- 79
- 80
- 81
- 82
- 83
open_tradingview_key: enter
quick_search_button: Ctrl+K
size_of_square: 200
square_hotkey: /
time_interval_button: ','
wait_value: 3
